### PR TITLE
Bump DC/OS Test Utils requirement

### PR DESCRIPTION
**Pull request by adamtheturtle**
This includes multiple changes but in particular we want to reduce the number of login attempts.

See https://jira.mesosphere.com/browse/DCOS-22022.

### CODE REVIEW

**Comment by adamtheturtle** [comment]
cc @mellenburg , @cprovencher, @Margaret, @sschneid for review.

**Review by margaret — APPROVED** [review]

**Comment by margaret** [comment]
CI failure is https://jira.mesosphere.com/browse/QUALITY-2025

**Review by mellenburg — CHANGES_REQUESTED** [review]
This line also needs to be kept in sync with this change: https://github.com/dcos/dcos-launch/blob/master/setup.py#L41

**Comment by adamtheturtle** [comment]
Thank you both.

@mellenburg I have made the requested change.

**Review by margaret — APPROVED** [review]

**Comment by adamtheturtle** [comment]
@Margaret @mellenburg can we get this merged please?

**Pull request merged**
