### PR TITLE
Update docker on install image pre-requisites.

### PR DESCRIPTION
**Pull request by orsenthil**
Update docker on install image pre-requisites.

- https://jira.mesosphere.com/browse/DCOS-37670

Update to 17.06.2 as listed in our support documentation at docs.mesosphere.com

---- 

## how did I test this?

* Launched a dcos-launch cluster.
* SSH to master
* Set `install_docker='true'` to force docker installation on image that has docker. Nothing to worry as this script removes the previous docker and installs it

* run the script

### Output

```
Downloading packages:
(1/2): container-selinux-2.55-1.el7.noarch.rpm                                                                                                       |  34 kB  00:00:00
(2/2): docker-ce-17.06.2.ce-1.el7.centos.x86_64.rpm                                                                                                  |  21 MB  00:00:03
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Total                                                                                                                                       6.6 MB/s |  21 MB  00:00:03
Running transaction check
Running transaction test
Transaction test succeeded
Running transaction
  Installing : 2:container-selinux-2.55-1.el7.noarch                                                                                                                    1/2
  Installing : docker-ce-17.06.2.ce-1.el7.centos.x86_64                                                                                                                 2/2
  Verifying  : docker-ce-17.06.2.ce-1.el7.centos.x86_64                                                                                                                 1/2
  Verifying  : 2:container-selinux-2.55-1.el7.noarch                                                                                                                    2/2

Installed:
  docker-ce.x86_64 0:17.06.2.ce-1.el7.centos

Dependency Installed:
  container-selinux.noarch 2:2.55-1.el7

Complete!
Created symlink from /etc/systemd/system/multi-user.target.wants/docker.service to /usr/lib/systemd/system/docker.service.
Prerequisites installed.

```

### Verify

[centos@ip-10-10-0-198 ~]$ sudo docker version
Client:
 Version:      17.06.2-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   cec0b72
 Built:        Tue Sep  5 19:59:06 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.06.2-ce
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   cec0b72
 Built:        Tue Sep  5 20:00:25 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

### CODE REVIEW

**Comment by orsenthil** [comment]
@margaret  / @cprovencher  - Please review.

**Comment by orsenthil** [comment]
@margaret  / @cprovencher  - Please review.

**Review by cprovencher — COMMENTED** [review]
Why are we not upgrading to latest stable release?
18.03.1-ce

**Comment by margaret** [comment]
Did this work when you tested it / how'd you test? Also +1 to cprovencher's question. Can you link the corresponding JIRA ticket?

**Comment by orsenthil** [comment]
@cprovencher  - We are updating to the "supported" version of DC/OS (as mentioned in docs.mesosphere.com)

**Comment by orsenthil** [comment]
@margaret  / @cprovencher  - Please take a look at the description on a) Need for this, and b) How it was tested manually.

**Review by colin-msphere — APPROVED** [review]

**Comment by margaret** [comment]
@orsenthil Is this PR considered blocked by https://jira.mesosphere.com/browse/DCOS_OSS-3594 ?

**Pull request closed without merging**
