### PR TITLE
Update CentOS AMIs

### PR DESCRIPTION
**Pull request by margaret**
To CentOS 7.4

See also: https://github.com/dcos/dcos/pull/1961

### CODE REVIEW

**Comment by margaret** [comment]
Tox tests failing with

```
[22:52:45][Step 1/1] 3366 INFO: Processing pre-find module path hook   distutils
[22:52:45][Step 1/1] 3370 INFO: distutils: retargeting to non-venv dir '/usr/lib/python3.5/distutils'
[22:52:52][Step 1/1] 10643 INFO: Loading module hooks...
[22:52:52][Step 1/1] 10643 INFO: Loading module hook "hook-boto3.py"...
[22:52:53][Step 1/1] 10890 INFO: Loading module hook "hook-xml.etree.cElementTree.py"...
[22:52:53][Step 1/1] 10890 INFO: Loading module hook "hook-xml.py"...
[22:52:53][Step 1/1] 10986 INFO: Loading module hook "hook-certifi.py"...
[22:52:53][Step 1/1] 10987 INFO: Loading module hook "hook-botocore.py"...
[22:52:53][Step 1/1] 11004 INFO: Loading module hook "hook-pkg_resources.py"...
[22:52:53][Step 1/1] 11056 INFO: Processing pre-safe import module hook   win32com
[22:52:53][Step 1/1] Traceback (most recent call last):
[22:52:53][Step 1/1]   File "<string>", line 2, in <module>
[22:52:53][Step 1/1] ImportError: No module named 'win32com'
```

**Comment by margaret** [comment]
(rebased)

**Comment by margaret** [comment]
Rebased again

**Comment by margaret** [comment]
tox failure is just that it can't find the win32 module

**Comment by margaret** [comment]
I accidentally triggered the onprem-gce test, but I'm just going to let it run so there wont be a ❌

**Comment by margaret** [comment]
Hmm... going to try running the zen template test manually so I can inspect the cluster before it gets torn down.

**Comment by margaret** [comment]
Tried to launch the CentOS zen template from this PR using this config.yaml which I copied from the `cat config.yaml` output in the CI build. I added the `aws_region` and `disable_rollback`.
```
---
launch_config_version: 1
template_url: https://s3.amazonaws.com/downloads.dcos.io/dcos/testing/master/cloudformation/el7-zen-1.json
provider: aws
key_helper: true
zen_helper: true
template_parameters:
    AdminLocation: 0.0.0.0/0
    PublicAgentInstanceCount: 1
    PrivateAgentInstanceCount: 1
ssh_user: centos
deployment_name: msy-20161027-1104
aws_region: us-west-2
disable_rollback: true
```


Stack is here (disabled the rollback) https://us-west-2.console.aws.amazon.com/cloudformation/home?region=us-west-2#/stack/detail?stackId=arn:aws:cloudformation:us-west-2:273854932432:stack%2Fmsy-20161027-1104-MasterStack-181TO7X0R8DC4%2F8a4a8f60-bb41-11e7-ac80-50d5ca789ee6

It has what appears to be the same issue as the CI build, where it says it did not receive a success signal.
```
  | 11:39:21 UTC-0700 | CREATE_FAILED | AWS::CloudFormation::Stack | msy-20161027-1104-MasterStack-181TO7X0R8DC4 | The following resource(s) failed to create: [MasterServerGroup].
-- | -- | -- | -- | -- | --
  | Physical ID:arn:aws:cloudformation:us-west-2:273854932432:stack/msy-20161027-1104-MasterStack-181TO7X0R8DC4/8a4a8f60-bb41-11e7-ac80-50d5ca789ee6
  | 11:39:20 UTC-0700 | CREATE_FAILED | AWS::AutoScaling::AutoScalingGroup | MasterServerGroup | Received 0 SUCCESS signal(s) out of 1.  Unable to satisfy 100% MinSuccessfulInstancesPercent requirement
  | Physical ID:msy-20161027-1104-MasterStack-181TO7X0R8DC4-MasterServerGroup-SD6KYIANAKIT
  | 11:39:19 UTC-0700 | UPDATE_IN_PROGRESS | AWS::AutoScaling::AutoScalingGroup | MasterServerGroup | Failed to receive 1 resource signal(s) for the current batch.  Each resource signal timeout is counted as a FAILURE.
```
I looked at the instance in the Master autoscaling group, and it was successfully created. However the logs on the instance says that it couldn't write pid files. Googling indicates that this was probably not run by an admin user.
```
Oct 27 18:11:38 localhost chronyd[565]: Fatal error : could not open lockfile /var/run/chronyd.pid for writing
Oct 27 18:12:06 ip-10-0-134-28 tuned[850]: 2017-10-27 18:12:06,241 ERROR    dbus.proxies: Introspect error on org.freedesktop.PolicyKit1:/org/freedesktop/PolicyKit1/Authority: dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NoReply: Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.
Oct 27 18:12:06 ip-10-0-134-28 tuned[850]: ERROR:dbus.proxies:Introspect error on org.freedesktop.PolicyKit1:/org/freedesktop/PolicyKit1/Authority: dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NoReply: Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.
Oct 27 18:12:07 ip-10-0-134-28 sshd[1427]: error: Couldn't create pid file "/var/run/sshd.pid": Permission denied
```
There are a whole bunch of logs like
```
Oct 27 18:12:35 ip-10-0-134-28 kernel: type=1130 audit(1509127955.968:368): pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg='unit=kdump comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=failed'
Oct 27 18:12:38 ip-10-0-134-28 systemd[1]: dcos-cfn-signal.service failed to run 'start-pre' task: No such file or directory
Oct 27 18:12:38 ip-10-0-134-28 systemd[1]: Unit dcos-cfn-signal.service entered failed state.
```
which is closer to the error message displayed in the cloudformation console.

Possibly related https://jira.mesosphere.com/browse/DCOS-17401

**Review by mellenburg — APPROVED** [review]
Changes passed tests in onprem installer. Failure in zen template tests are not relevant to dcos-launch in this case

**Pull request merged**
