### PR TITLE
Adding `rhel-7-dcos-prereqs` with updated AMIs

### PR DESCRIPTION
**Pull request by sschneid**
Removing `rhel-7` as we don't use a RedHat 7 AMI without preinstalled
DC/OS prerequisites.

All AMIs are Red Hat 7.4.

### CODE REVIEW

**Review by margaret — CHANGES_REQUESTED** [review]
Thanks! Can you just update this to Red Hat? https://github.com/dcos/dcos-launch/blob/831296608580b86c74147954e5388f8053fac342/dcos_launch/platforms/aws.py#L600

**Comment by mellenburg** [comment]
Just gonna run the automated CI integration test against this new image and then lets merge this!

**Comment by sschneid** [comment]
@margaret added an inline `Red Hat 7.4` comment.

**Comment by mellenburg** [comment]
CI run: https://teamcity.mesosphere.io/viewLog.html?buildId=878721&tab=buildResultsDiv&buildTypeId=DcosIo_DcosLaunch_IntegrationTests_Onprem

**Comment by sschneid** [comment]
CI might fail without `bootstrap_os_name` set in the cluster config (authentication fails when the bootstrap node uses a different username than the host, `centos` vs `ec2-user` in this case)... or maybe that's just when `ssh_user` is explicitly set?  👀

**Review by margaret — APPROVED** [review]

**Comment by mellenburg** [comment]
@sschneid thanks for pointing that out. We need to make a `default_setter` for boostrap_os_name then, but that can be a different PR

**Comment by margaret** [comment]
`ssh_user` is required in aws onprem. But yeah, I think this would break if you had different a different OS in the bootstrap node and cluster nodes because it would use `ssh_user` to log in for both of them.

**Comment by sschneid** [comment]
Here's a CI run using Red Hat for the bootstrap: https://teamcity.mesosphere.io/viewLog.html?buildId=878734&tab=buildResultsDiv&buildTypeId=DcosIo_DcosLaunch_IntegrationTests_Onprem

**Comment by mellenburg** [comment]
on further consideration I guess the best way is just adding a distinct bootstrap_ssh_user rather than forcing some equality between bootstrap_os_name and os_name given that mean you would always need an OS that has the same name as the bootstrap and ideally you should never have to touch the bootstrap stuff if you don't care to

**Comment by sschneid** [comment]
https://teamcity.mesosphere.io/viewLog.html?tab=buildLog&logTab=tree&filter=debug&expand=all&buildId=878734&_focus=241

````
[2017-11-30 23:24:10,549|root|INFO]: {
    "docker_client_version": "17.05.0-ce",
    "docker_server_version": "17.05.0-ce",
    "system_platform": "Linux-3.10.0-693.5.2.el7.x86_64-x86_64-with-redhat-7.4-Maipo",
    "system_platform_release": "3.10.0-693.5.2.el7.x86_64",
    "system_platform_system": "Linux",
    "system_platform_version": "#1 SMP Fri Oct 13 10:46:25 EDT 2017"
}
````

🎆

**Comment by sschneid** [comment]
(and for posterity, my manual integration test on a `dcos-launch` provisioned cluster):

````
$ dcos-launch pytest
[2017-11-30 14:45:31,900|dcos_launch.util|INFO]: Running integration test...
Exit request sent.
============================= test session starts ==============================
platform linux -- Python 3.6.3, pytest-3.0.3, py-1.4.31, pluggy-0.4.0
rootdir: /opt/mesosphere/packages/dcos-integration-test--4a8502acbcd01ecd7948b09a71794edb26b46043, inifile:
plugins: teamcity-messages-1.19
collected 141 items

test_composition.py .
test_applications.py .......
test_auth.py ..
test_composition.py .....
test_dcos_diagnostics.py ..............s....
test_dcos_log.py .....ss.......
test_endpoints.py ..................
test_mesos.py ...s
test_metrics.py ....
test_misc.py ...
test_networking.py .....................................s...
test_packaging.py .s
test_rexray.py s
test_rlimit.py .
test_service_discovery.py .........
test_sysctl.py .
test_ucr.py ......
test_units.py ...

=================== 134 passed, 7 skipped in 2439.86 seconds ===================
````

**Review by mellenburg — APPROVED** [review]

**Comment by mellenburg** [comment]
Thanks scott!

**Pull request merged**
