### PR TITLE
Remove nogroup creation 

### PR DESCRIPTION
**Pull request by janisz**
## High-level description (required)

What features does this change enable? / What bugs does this change fix?

## Corresponding tickets (required)

These JIRA ticket(s) must be updated (ideally closed) in the moment this PR lands:

  - [COPS-5220](https://jira.mesosphere.com/browse/COPS-5220) 
  - https://github.com/dcos/dcos/pull/6166

## Related tickets (optional)

Other tickets related to this change

  - [DCOS-<number>](https://jira.mesosphere.com/browse/DCOS-<number>) Foo the Bar so it stops Bazzing.

## Related PRs (optional)

Is this change going to be propagated up into dcos-integration-tests in dcos/dcos or another repo? Does this change require changes in dcos-test-utils? Link the corresponding PRs here:

## Checklist for all PRs

  - [ ] Included a test which will fail if code is reverted but test is not. If there is no test please explain here:
  - [ ] **Added or updated any relevant documentation**

[Integration tests](https://teamcity.mesosphere.io/project.html?projectId=DcosIo_DcosLaunch&branch_DcosIo_DcosLaunch=%3Cdefault%3E) were run and

  - [ ] AWS Cloudformation Simple (link to job: )
  - [ ] Azure Resource Manager (link to job: )
  - [ ] Onprem-AWS (link to job: )
  - [ ] Onprem-GCE (link to job: )

**PLEASE FILL IN THE TEMPLATE ABOVE** / **DO NOT REMOVE ANY SECTIONS ABOVE THIS LINE**

## Instructions and review process

**What is the review process and when will my changes land?**

All PRs should have two approved [pull request reviews](https://help.github.com/articles/about-pull-request-reviews/).

Reviewers should be:
* Developers who understand the code being modified.
* Developers responsible for code that interacts with or depends on the code being modified.

It is best to proactively ask for 2 reviews by @mentioning the candidate reviewers in the PR comments area. The responsibility is on the developer submitting the PR to follow-up with reviewers and make sure a PR is reviewed in a timely manner.

### CODE REVIEW

**Review by drewvanstone — APPROVED** [review]

**Comment by janisz** [comment]
@mesosphere-mergebot request-review @drewvanstone @br-lewis @makkes @bamarni @rgo3

**Review by br-lewis — APPROVED** [review]

**Review by makkes — APPROVED** [review]

**Comment by makkes** [comment]
@mesosphere-mergebot request-review @fatz

**Comment by makkes** [comment]
@fatz Would you please have a look at this as well?

**Comment by janisz** [comment]
@fatz Can you take a look?

**Review by fatz — CHANGES_REQUESTED** [review]
Correct me if I'm wrong but this drops support for previous DC/OS versions as nogroup is still part of their prerequisites

**Comment by janisz** [comment]
We would like to backport this to previous version. We shouldn't use `nogroup` in any of our supported dcos version.

**Comment by janisz** [comment]
https://github.com/dcos/dcos-ansible/pull/68

**Comment by fatz** [comment]
well former versions are still in use and should also be debuggable 

If this matters for dcos-launch is something I cannot judge but even if this is getting backported to other minor versions it still means former patch versions stay unusable

**Comment by janisz** [comment]
@fatz So what we should do with it?

**Comment by fatz** [comment]
> @fatz So what we should do with it?
I think this needs conditions based on DC/OS version to support previous not patched releases which means we need semver patchlevel greater than or something like this

**Comment by janisz** [comment]
@cprovencher Can you take a look?

**Comment by cprovencher** [comment]
@janisz Those prereqs scripts don't run by default. I don't know that anyone is using them. Most people that use prereqs scripts use their own. nogroup is included in the default AMIs here: https://github.com/dcos/dcos-launch/blob/master/dcos_launch/platforms/aws.py#L668
If we want to change the default behavior, we need to build new images without nogroup and update them here.

**Comment by janisz** [comment]
> If we want to change the default behavior, we need to build new images without nogroup and update them here.

Let's do that

**Comment by drewvanstone** [comment]
I think we should just close this PR at this point. `nogroup` will continue to get created for all versions of DC/OS. However, after version 2.0 the group will no longer be needed. Ideally if (when?) we switch our CI/CD to use the universal installer, there will be only a single place where groups get created. As it stands, it sounds like there are a number of prereq scripts that each would need to be updated to check for the DC/OS version, and create the group if older than version 2.0. 

So switching to universal installer sometime in the future will ultimately fix this issue. In the meantime, it shouldn't cause any harm to keep the group around.

**Pull request closed without merging**
