### PR TITLE
`1.0.0` explicit versioning

### PR DESCRIPTION
**Pull request by sschneid**
- `dcos-launch version` command
- CHANGELOG.md

### CODE REVIEW

**Review by colin-msphere — APPROVED** [review]

**Review by mellenburg — CHANGES_REQUESTED** [review]
Thanks for adding this @sschneid but a few points:
* dcos-launch is not in a great state right now. It can only deploy on one onprem image. I would much prefer that we wait to get this in https://github.com/dcos/dcos-launch/pull/55 If we are branching for a stable release, I strongly prefer that the revision be something I want people to use
*  docopt as a --version option that does what the version command does by default. It sees overkill and like clutter to have a whole command for this
* I am very hesitant to label this as version `1.0.0` Lets call this `0.1.0` if anything. I figure `1.0.0` is reserved for when this tool is product-ready an not just a stop-gap to support CI and the disappointing onprem installer

**Comment by sschneid** [comment]
```
$ dcos-launch --version
dcos-launch 1.0.0
```
Hmm... seems like I should've read about docopt.  :)

I think `0.1.0` is appropriate given the project state.  My main motivation for getting releases versioned is for support -- if users are downloading binaries, it's useful to be able to pin bugs (and features) to versions and suggest upgrades.

**Comment by mellenburg** [comment]
Totally agree its about time this has some better versioning on it. Do you think we should add (or rather, HOW should we add) some tagged sub folders to the download bucket? E.G. right now we have 
`dcos-launch/bin/PLATFORM/dcos-launch` but we could also have `dcos-launch/RELEASE/bin/PLATFORM/dcos-launch` ?

**Comment by mellenburg** [comment]
Totally agree its about time this has some better versioning on it. Do you think we should add (or rather, HOW should we add) some tagged sub folders to the download bucket? E.G. right now we have 
`dcos-launch/bin/PLATFORM/dcos-launch` but we could also have `dcos-launch/RELEASE/bin/PLATFORM/dcos-launch` and then maybe on every push to the master release we s3 cp to the unlabeled/top-level bucket that everyone is currently using

**Comment by margaret** [comment]
+1 0.1 instead of 1.0. #55 is almost done 😬

**Comment by colin-msphere** [comment]
I recommend using `master`, `latest`, or `snapshot` to signify non-versioned artifact. That identifier can either be in the artifact's name (`dcos-launch-latest`) or path (`dcos-launch/latest/bin/PLATFORM/dcos-launch`).

EDIT: It is an extra piece of information to let the user know it is not a release, in the case where the user is not aware of release paths.

**Comment by margaret** [comment]
Can rebase onto master now (PR 55 merged)

**Comment by sschneid** [comment]
Replaced by #59.

**Pull request closed without merging**
