### PR TITLE
Don't crash during onprem when launching clusters with 0 public or private nodes

### PR DESCRIPTION
**Pull request by margaret**
https://jira.mesosphere.com/browse/QUALITY-1732

### CODE REVIEW

**Comment by margaret** [comment]
cluster comes up, the failure is that test_signal_service integration test that's been failing on dcos-launch master for a while 🤔 I think it's this issue https://jira.mesosphere.com/browse/DCOS-9700?jql=text%20~%20%22test_signal_service%22

**Comment by mellenburg** [comment]
@margaret yeah... I was trying to look into that more and then got distracted. That particular ticket I think should be closed... that was for instability in the EE tests, whereas now we see that this is only an issue in this case where only test_composition.py is ran. So, I feel like we should be able to just improve the wait-for-cluster-up code.

All that being said, we shouldnt block this change on that

**Comment by margaret** [comment]
@mellenburg It worked with a config specifying zero public agents 🚢 
```
---
launch_config_version: 1
deployment_name: msy-launch-20180110-1054
installer_url: https://downloads.mesosphere.com/dcos-enterprise/testing/pull/1607/dcos_generate_config.ee.sh
platform: aws 
provider: onprem
aws_region: us-west-2
key_helper: true
os_name: cent-os-7-dcos-prereqs
instance_type: m4.xlarge
num_masters: 1
num_private_agents: 1
num_public_agents: 0
tags:
  expiration: 2hours
  owner: msy
dcos_config:
  cluster_name: DC/OS OnPrem (msy)
  master_discovery: static
  exhibitor_storage_backend: zookeeper
  exhibitor_zk_path: /exhibitor
  resolvers:
    - 8.8.8.8
    - 8.8.8.4
```

**Review by mellenburg — APPROVED** [review]
:ship:

**Comment by mellenburg** [comment]
Failure of `integration-test-onprem-aws` unrelated to this change, so we're going ahead with merge

**Pull request merged**
