### PR TITLE
support `license_key_filename` in `dcos_config`

### PR DESCRIPTION
**Pull request by sschneid**
Part of [DCOS-19503](https://jira.mesosphere.com/browse/DCOS-19503) "DC/OS ee CI TeamCity Update to use Licensing"

### CODE REVIEW

**Review by margaret — APPROVED** [review]

**Comment by mellenburg** [comment]
@margaret thanks for this contribution, however I have some work in progress that I plan to ship before the end of the week that will invalidate this:
https://github.com/dcos/dcos-launch/tree/genconf_dir

Specifically, my change will allow users to create a `genconf` folder in accordance with the install docs and then that whole folder will be recursively copied to the bootstrap host. Thus, we will not need to add these individual hooks for each file that a user would like to provide.

So, in light of that, is this still useful to merge if its going to get steamrolled? I would prefer holding off so I can avoid a merge-conflict, but if this unblocks someone for the next few days I can live with fixing that conflict

**Comment by margaret** [comment]
Oops, yeah, didn't know about that either. Holding off on this PR sounds better.

**Review by margaret — CHANGES_REQUESTED** [review]
see previous comments - this is in conflict with another PR

**Comment by sschneid** [comment]
Having a `genconf/` directory rather than per-file piecemeal is fine with me.  I believe @branden has also made `license_key_contents` configurable within genconf's `config.yaml` as well, which renders passing a license file through dcos-launch (and this PR) unnecessary.  Closing.

**Pull request closed without merging**
